name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  lint:
   runs-on: ubuntu-latest
   steps:
     - name: Lint Code Base
       uses: docker://github/super-linter:v2.2.0
  composer-install:
    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        composer: [lowest, current, highest]
    needs: lint
    runs-on: ubuntu-latest
    container:
      image: wyrihaximusnet/php:${{ matrix.php }}-nts-alpine3.12-dev-root
    steps:
      - uses: actions/checkout@v1
      - name: Cache composer packages
        uses: actions/cache@v1
        with:
          path: ./vendor/
          key: ${{ matrix.composer }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Dependencies
        run: composer update --prefer-lowest --no-progress --ansi --no-interaction --prefer-dist -o
        if: matrix.composer == 'lowest'
      - name: Install Dependencies
        run: composer install --ansi --no-progress --no-interaction --prefer-dist -o
        if: matrix.composer == 'current'
      - name: Install Dependencies
        run: composer update --ansi --no-progress --no-interaction --prefer-dist -o
        if: matrix.composer == 'highest'
  qa:
    strategy:
      fail-fast: false
      matrix:
        php: [7.4]
        composer: [lowest, current, highest]
        qa: [lint, cs, stan, psalm, unit, infection, composer-require-checker, composer-unused, backward-compatibility-check]
    needs: composer-install
    runs-on: ubuntu-latest
    container:
      image: wyrihaximusnet/php:${{ matrix.php }}-nts-alpine3.12-dev-root
    steps:
      - uses: actions/checkout@v1
      - name: Cache composer packages
        uses: actions/cache@v1
        with:
          path: ./vendor/
          key: ${{ matrix.composer }}-${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
      - name: Install Dependencies
        run: (test -f vendor && true ) || composer update --prefer-lowest --no-progress --ansi --no-interaction --prefer-dist -o
        if: matrix.composer == 'lowest'
      - name: Install Dependencies
        run: (test -f vendor && true ) || composer install --ansi --no-progress --no-interaction --prefer-dist -o
        if: matrix.composer == 'current'
      - name: Install Dependencies
        run: (test -f vendor && true ) || composer update --ansi --no-progress --no-interaction --prefer-dist -o
        if: matrix.composer == 'highest'
      - name: Fetch Tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
        if: matrix.qa == 'backward-compatibility-check'
      - run: make ${{ matrix.qa }}
